# Generated by Django 5.1.7 on 2025-03-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_user_id_project_user_project_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
